//
// Created by Jack on 2019/7/22.
//

#ifndef ASF_ANDROIDCMD_H
#define ASF_ANDROIDCMD_H

#define ACCMD_MESSAGEBOX 1
#define ACCMD_SHOWMESSAGE 2
#define ACCMD_VIBRATE 3
#define ACCMD_CALLANDROID 4
#define ACCMD_SCREENSHOT 5
#define ACCMD_GETDISPLAYINFO 6
#define ACCMD_REQUESTCONTROL 7

#define ACCMD_FINDVIEWBYTEXT 11
#define ACCMD_FINDVIEWBYID 12
#define ACCMD_PERFORMVIEWCLICK 13
#define ACCMD_PERFORMBACKCLICK 14
#define ACCMD_PERFORMSCROLLBACKWARD 15
#define ACCMD_PERFORMSCROLLFORWARD 16
#define ACCMD_INPUTTEXT 17
#define ACCMD_ENUMNODEINFO 18

#endif //ASF_ANDROIDCMD_H
